name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo snap install zig --classic --beta
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_zig_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: zig run example.zig -I/usr/include/postgresql -lc -lpq
